# Generated by Django 2.0.5 on 2018-11-08 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0002_auto_20181108_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('app_desc', models.CharField(max_length=100)),
                ('use_yn', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('host_ip', models.CharField(max_length=100)),
                ('host_desc', models.CharField(max_length=100)),
                ('use_yn', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTranInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_mid', models.CharField(max_length=100)),
                ('tran_w1_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w1_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w1_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w1_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w2_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w2_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w2_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w2_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w3_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w3_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w3_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w3_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w4_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w4_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w4_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w4_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w5_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w5_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w5_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_w5_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('use_yn', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTranInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_mid', models.CharField(max_length=100)),
                ('tran_d1_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d1_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d1_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d1_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d2_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d2_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d2_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d2_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d3_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d3_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d3_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d3_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d4_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d4_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d4_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d4_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d5_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d5_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d5_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d5_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d6_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d6_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d6_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d6_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d7_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d7_errcnt', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d7_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_d7_errratio', models.CharField(blank=True, max_length=100, null=True)),
                ('use_yn', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
